default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: wolo

development:
  <<: *default
  database: election_analytics_development

test:
  <<: *default
  database: election_analytics_test

production:
  <<: *default
  database: election_analytics_production
  username: election_analytics
  password: <%= ENV['election_analytics_DATABASE_PASSWORD'] %>
